algoritmo "semnome"
// Função : Crie um algoritmo
// Autor :
// Data : 21/08/2023
// Seção de Declarações 
var

 gasto, mercadoria, desconto: real

inicio

escreval("-------------------BLACK FRIDAY---------------")
escreval()

escreval("Digite valor que você gastou:")
leia(gasto)

escreval("Digite o valor da mercadoria:")
leia(mercadoria)

escreval("O valor do desconto foi de:", (gasto) - (mercadoria))


fimalgoritmo
