algoritmo "Dobro e Triplo"
// Função : Faça um algoritmo que o usuário digite um número e obtenha
//como resultado o dobro e o triplo do número digitadoAlgoritmo "Dobro e Triplo"
// Data : 22/08/2023
// Seção de Declarações 
var

num, resultado1, resultado2: inteiro

inicio

escreval("____________DOBRO E TRIPLO_________________")
escreval()

escreval("Digite um numero:")
leia(num)

escreval("O dobro do valor é:", (num * 2))
escreval("O triplo do valor é:", (num * 3))

fimalgoritmo
