algoritmo "semnome"
// Função :
// Autor :
// Data : 13/11/2023
// Seção de Declarações 
var

jogo: vetor [1..9] de caracter
inicio
// Seção de Comandos

jogo[1,1] <- "1"
jogo[1,] <- "2"
jogo[] <- "3"
jogo[] <- "4"
jogo[] <- "5"
jogo[] <- "6"
jogo[] <- "7"
jogo[] <- "8"
jogo[] <- "9"

escreval("                 ")
escreval("____|_____|____")
escreval("    |     |        ")
escreval("____|_____|____")
escreval("    |     |        ")
fimalgoritmo
