algoritmo "somaDoisNumeros"
// Função : Crie um algoritmo que peça dois numeros e faça a soma entre eles
// Autor :   Gabrielli
// Data : 14/08/2023
// Seção de Declarações 
var
numero1: real
numero2: real

inicio
escreval ("______________Soma de dois numeros________________")
escreval()

escreval("Digite o primeiro numero:")
leia (numero1)
escreval()

escreval("Digite o segundo numero:")
leia (numero2)
escreval()

escreval("O resultado da soma é", numero1 + numero2,".")

fimalgoritmo
