algoritmo "semnome"
// Função : Crie um algoritmo que calcule triangulo
// Autor :
// Data : 21/08/2023
// Seção de Declarações 
var

base: real
altura: real

inicio

escreval("----------------TRIANGULO-----------")
escreval()

escreval("Digite o valor da base do triângulo:")
leia(base)

escreval("Digite o valor da altura:")
leia(altura)

escreval("A área d triângulo será:", base*altura/2)

fimalgoritmo
